### PR TITLE
Declare namespace on class

### PR DESCRIPTION
**Pull request by meysampg**
For use class on frameworks that use PSR-4 standards, class must be namespaced. I declare namespace 'farhadi' for this class and enforce all other classes to use root namespace.

### CODE REVIEW

**Comment by farhadi** [comment]
Thanks!

**Comment by salarmehr** [comment]
It was better if you only add `use DateTimeZone;` in the beginning of the file instead of adding slash everywhere. Also conventionally namespace are in PaskalCase `farhadi` -> `Farhadi`

**Comment by farhadi** [comment]
@salarmehr Thanks for your suggestions. But these are just personal preferences, and there is not any strict rule about them in any of PSR specs nor the code is fully compliant with PSR specs.

So I will keep the namespace in lower case, but about using classes in the global namespace, I also prefer your approach and will fix it later.

**Comment by salarmehr** [comment]
I never see any vendor code using `lowerCase` for namespace. It cause your code seems novice for new potential user.

**Comment by farhadi** [comment]
Lithium is a member of PHP Framework Interop Group and they use lower case namespaces. So it's not unusual. 

See this file as an example:
https://github.com/UnionOfRAD/lithium/blob/master/core/Object.php

**Pull request merged**
